import { family, flatten, hex6 } from "./dtcg.ts";
import type { PackData } from "./pack.ts";

/** What the template's clrScheme / fontScheme should contain, according to tokens.json. */
export function pptxTheme(pack: PackData): { colors: Record<string, string>; fonts: Record<string, string> } {
  const colors: Record<string, string> = {};
  const fonts: Record<string, string> = {};
  for (const [k, v] of pack.values) {
    const m = /^theme\.([^.]+)$/.exec(k);
    if (m?.[1]) colors[m[1]] = hex6(v);
    const f = /^theme\.font\.(major|minor)$/.exec(k);
    if (f?.[1]) fonts[f[1]] = family(v);
  }
  return { colors, fonts };
}

const list = (items: string[] | undefined) => (items ?? []).map((i) => `- ${i}`).join("\n");

/** DESIGN.md in the OpenDesign 9-section shape, adapted to a slide canvas. Generated, never edited. */
export function designMd(pack: PackData): string {
  const { manifest: m, notes, values } = pack;
  const flat = flatten(pack.tokens);
  const get = (p: string) => values.get(p);
  const roleColors = [...flat.keys()]
    .filter((k) => k.startsWith("role.color."))
    .map((k) => `| \`${k.slice(11)}\` | \`#${hex6(get(k))}\` | ${flat.get(k)?.$description ?? ""} |`);
  const palette = [...flat.entries()]
    .filter(([k, t]) => t.$type === "color" && !k.startsWith("role.") && !k.startsWith("theme."))
    .map(([k, t]) => `| \`${k}\` | \`#${hex6(get(k))}\` | ${t.$description ?? ""} |`);
  const sizes = [...flat.keys()]
    .filter((k) => k.startsWith("role.size."))
    .map((k) => `${k.slice(10)} ${String(get(k))}`)
    .join(" · ");
  const fontRole = (r: string) =>
    `- **${r.charAt(0).toUpperCase()}${r.slice(1)}:** ${family(get(`role.font.${r}`))} (weight ${String(get(`role.fontWeight.${r}`))}), fallback ${m.fonts.fallback[r] ?? m.fonts.fallback.body}`;
  const cols = Object.entries(m.grid.columns)
    .map(([n, xs]) => `${n}-up at x = ${xs.join(" / ")} in`)
    .join("; ");
  const t = m.grid.title;
  const single = (m.lint.single_use_colors ?? []).map((p) => `\`${p}\``).join(", ");

  return `# ${notes.title ?? m.name}

> Brand pack \`${m.id}\` v${m.version}. Generated by Calque from \`tokens.json\`, \`pack.yaml\` and
> \`design-notes.yaml\`: edit those, never this file.

## Visual Theme & Atmosphere
${notes.atmosphere?.trim() ?? "_Not described._"}

## Color Palette & Roles
| Role | Hex | Use |
| --- | --- | --- |
${roleColors.join("\n")}

Full palette (the lint rejects any other colour):

| Token | Hex | Note |
| --- | --- | --- |
${palette.join("\n")}
${single ? `\nAt most one element per slide may use: ${single}.` : ""}

## Typography Rules
${["display", "body", "label"].map(fontRole).join("\n")}
- Scale: ${sizes}
- Replace text run by run so each run keeps its font and size.

## Component Stylings
- Strokes: hairline ${String(get("role.stroke.hairline"))}, link ${String(get("role.stroke.link"))}, emphasis ${String(get("role.stroke.emphasis"))}.
${Object.entries(notes.elements ?? {})
  .map(([k, v]) => `- **${k}:** ${v.trim()}`)
  .join("\n")}

## Layout Principles
- Canvas ${pack.canvas.width_in} × ${pack.canvas.height_in} in. Margin ${m.grid.margin_in} in.
- Columns: ${cols}.
- Title box L${t.left_in} T${t.top_in} W${t.width_in} H${t.height_in}${t.max_chars ? `, one line of at most ${t.max_chars} characters` : ""}.
- Body band from T${m.grid.body_top_in} in; nothing below the footer line at T${m.grid.footer_top_in} in.

## Depth & Elevation
${notes.elements?.depth ? "See Component Stylings." : "Flat: no shadows, no 3D, no gradients unless the template carries them."}

## Do's and Don'ts
${list(notes.do?.map((d) => `✅ ${d}`))}
${list(notes.dont?.map((d) => `❌ ${d}`))}

## Canvas
Slides, not screens: a fixed ${pack.canvas.width_in} × ${pack.canvas.height_in} in canvas. Text never shrinks
to fit; tighten the copy before enlarging a box.

## Agent Prompt Guide
- Use the roles above; never invent a hex value or a font.
- Unknown value: write ${Object.entries(m.missing_value)
    .map(([l, v]) => `\`${v}\` (${l})`)
    .join(", ")}, in the deck's language.
${list(notes.agent)}
`;
}
