// pnpm pack:sync <pack-id>: rebuild a pack's synced files from the pinned sources in source.yaml.
// Deterministic: running it twice leaves a clean git diff.
import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, globSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve as resolvePath } from "node:path";
import { parse } from "yaml";
import { designMd, importNamed, readPack, type TokenTree } from "@calque/design";

interface Source { repo: string; ref: string }
interface SourceFile {
  sources: Record<string, Source>;
  copy: { to: string; from: string | string[] }[];
  tokens: { import: string; groups: string[]; prefix: string; overlay: string };
}

const root = resolvePath(import.meta.dirname, "..");
const id = process.argv[2];
if (!id) throw new Error("usage: pnpm pack:sync <pack-id>");
const packDir = join(root, "packs", id);
const spec = parse(readFileSync(join(packDir, "source.yaml"), "utf8")) as SourceFile;

const git = (cwd: string, ...args: string[]) => execFileSync("git", args, { cwd, encoding: "utf8" }).trim();

function checkout(name: string): string {
  const s = spec.sources[name];
  if (!s) throw new Error(`unknown source: ${name}`);
  const dir = join(root, ".cache", "pack-sources", `${s.repo.replace("/", "__")}@${s.ref}`);
  if (!existsSync(dir)) {
    mkdirSync(dirname(dir), { recursive: true });
    execFileSync("gh", ["repo", "clone", s.repo, dir, "--", "--quiet", "--no-checkout"], { stdio: "inherit" });
    git(dir, "checkout", "--quiet", s.ref);
  }
  return dir;
}

function sourcePaths(ref: string): string[] {
  const [name, rel] = ref.split(/:(.*)/s) as [string, string];
  const dir = checkout(name);
  const hits = rel.includes("*") ? globSync(rel, { cwd: dir }).sort() : [rel];
  if (!hits.length) throw new Error(`no match: ${ref}`);
  return hits.map((h) => join(dir, h));
}

for (const { to, from } of spec.copy) {
  const target = join(packDir, to);
  const files = (Array.isArray(from) ? from : [from]).flatMap(sourcePaths);
  if (to.endsWith("/")) {
    mkdirSync(target, { recursive: true });
    for (const f of files) copyFileSync(f, join(target, basename(f)));
  } else if (files.length === 1 && files[0]) {
    mkdirSync(dirname(target), { recursive: true });
    copyFileSync(files[0], target);
  } else {
    writeFileSync(target, files.map((f) => readFileSync(f, "utf8").trimEnd()).join("\n\n---\n\n") + "\n");
  }
}

const tokSrc = sourcePaths(spec.tokens.import)[0] ?? "";
const imported = importNamed(JSON.parse(readFileSync(tokSrc, "utf8")) as TokenTree, spec.tokens.groups, spec.tokens.prefix);
const overlay = JSON.parse(readFileSync(join(packDir, spec.tokens.overlay), "utf8")) as TokenTree;
const merge = (a: TokenTree, b: TokenTree): TokenTree => {
  const out: TokenTree = { ...a };
  for (const [k, v] of Object.entries(b)) {
    const prev = out[k];
    out[k] = prev && typeof prev === "object" && typeof v === "object" && v && !("$value" in v)
      ? merge(prev as TokenTree, v as TokenTree)
      : v;
  }
  return out;
};
const tokens = merge(imported, overlay);
tokens.$description = `Generated by pack:sync from ${spec.tokens.import} (groups ${spec.tokens.groups.join(", ")}) + ${spec.tokens.overlay}. Do not edit.`;
writeFileSync(join(packDir, "tokens.json"), JSON.stringify(tokens, null, 2) + "\n");

execFileSync("uv", ["run", "--project", join(root, "engine"), "python", "-m", "calque_engine", "extract-template",
  join(packDir, "template.pptx"), "--map", join(packDir, "template-map.yaml")], { stdio: "inherit" });

writeFileSync(join(packDir, "DESIGN.md"), designMd(readPack(packDir)));

const rows = Object.entries(spec.sources).map(([name, s]) => {
  const dir = checkout(name);
  return `| ${name} | [${s.repo}](https://github.com/${s.repo}) | \`${s.ref}\` | ${git(dir, "rev-parse", "HEAD").slice(0, 12)} | ${git(dir, "log", "-1", "--format=%cs")} |`;
});
writeFileSync(join(packDir, "SOURCE.md"), `# Sources of the \`${id}\` pack

Generated by \`pnpm pack:sync ${id}\` from \`source.yaml\`. Do not edit the synced files by hand:
change the pinned ref in \`source.yaml\` and re-run the sync.

| Source | Repo | Ref | Commit | Commit date |
| --- | --- | --- | --- | --- |
${rows.join("\n")}

| Pack file | From |
| --- | --- |
${spec.copy.map((c) => `| \`${c.to}\` | ${(Array.isArray(c.from) ? c.from : [c.from]).map((f) => `\`${f}\``).join("<br>")} |`).join("\n")}
| \`tokens.json\` | \`${spec.tokens.import}\` + \`${spec.tokens.overlay}\` |
| \`template-map.yaml\` | extracted from \`template.pptx\` (reviewed keys kept) |
| \`DESIGN.md\` | generated from \`tokens.json\`, \`pack.yaml\`, \`design-notes.yaml\` |
`);
console.log(`synced ${id}`);
